language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

branches:
  only:
    - staging
    - trying
    - master

install:
  - python setup.py build

script: "python test.py"
