language: python
dist: trusty

matrix:
  include:
  - python: "2.7"
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
    dist: xenial
    sudo: required

branches:
  only:
    - staging
    - trying
    - master

install:
  - python setup.py build

script: "python test.py"
